
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      cd data && docker run --name yottadb --name=yottadb -dt -v $PWD:/data ramb0/yottadb-broot /opt/yottadb/current/ydb

vscode:
  extensions:
    - formulahendry.code-runner
    - https://github.com/RamSailopal/YottaDB-dashboard/raw/main/Vista-Docker/theiaa-build/dsilin.mumps-0.1.1.vsix
