
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      ln -s /workspace/YottaDB-gitpod/data/r1.32_x86_64/r /workspace/YottaDB-gitpod/data/r && cd compose && docker-compose up

vscode:
  extensions:
    - formulahendry.code-runner
    - https://github.com/RamSailopal/YottaDB-dashboard/raw/main/Vista-Docker/theiaa-build/dsilin.mumps-0.1.1.vsix
    - mtxr.sqltools-driver-mysql
