version: "2"
services:
 mysql:
   image: mysql
   container_name: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: present
   networks:
      - yottanet
   volumes:
     - ../data:/home/mysql
     
 phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
       - yottanet

 yottadb:
   image: docker.io/yottadb/yottadb-base
   container_name: yottadb
   networks:
      - yottanet
   volumes:
      - ../data:/data
   entrypoint: [ "/bin/bash", "-c", "tail -f /dev/null" ]
   
 yottagui:
   image: docker.io/samindcon/vehu
   container_name: yottagui
   ports:
     - 8001:8001
     - 9430:9430
     - 1338:1338
     - 8089:8089
   networks:
      - yottanet
   volumes:
      - ../data/r1.32_x86_64/g:/data/r1.32_x86_64/g
      - ../data:/data
   environment:
      - ydb_dir=/data
      - gtmdir=/data
      - gtmgbldir=/home/vehu/g/yottadb.gld
      
networks:
    yottanet:
